'use strict';
/**
 * Ticket transcripts. Renders a channel's history into a self-contained,
 * styled HTML file that can be attached to a Discord message and opened in any
 * browser — no hosting, no external assets.
 */
const { AttachmentBuilder } = require('discord.js');
const config = require('./config');

const esc = (s) => String(s ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

/** Fetch up to `limit` messages, oldest first. */
async function collect(channel, limit = 1000) {
  const out = [];
  let before;
  while (out.length < limit) {
    const batch = await channel.messages.fetch({ limit: 100, before }).catch(() => null);
    if (!batch || !batch.size) break;
    out.push(...batch.values());
    before = batch.last().id;
    if (batch.size < 100) break;
  }
  return out.reverse();
}

function renderHtml(channel, messages, meta) {
  const rows = messages.map((m) => {
    const time = new Date(m.createdTimestamp).toLocaleString();
    const attachments = [...m.attachments.values()]
      .map((a) => `<a class="att" href="${esc(a.url)}">📎 ${esc(a.name)}</a>`).join(' ');
    const embeds = m.embeds.map((e) => `
      <div class="embed">
        ${e.title ? `<div class="et">${esc(e.title)}</div>` : ''}
        ${e.description ? `<div class="ed">${esc(e.description)}</div>` : ''}
        ${(e.fields || []).map((f) => `<div class="ef"><b>${esc(f.name)}</b><br>${esc(f.value)}</div>`).join('')}
      </div>`).join('');

    return `
    <div class="msg">
      <div class="meta"><span class="author">${esc(m.author.tag)}</span><span class="time">${esc(time)}</span></div>
      ${m.content ? `<div class="content">${esc(m.content)}</div>` : ''}
      ${embeds}${attachments ? `<div class="atts">${attachments}</div>` : ''}
    </div>`;
  }).join('\n');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(channel.name)} — transcript</title>
<style>
  :root { color-scheme: dark; }
  body { margin:0; background:#0d1117; color:#e6edf3; font:15px/1.6 -apple-system,Segoe UI,Roboto,sans-serif; }
  header { padding:24px 28px; border-bottom:1px solid #21262d; background:#161b22; }
  h1 { margin:0 0 6px; font-size:20px; }
  .sub { color:#8b949e; font-size:13px; }
  main { max-width:900px; margin:0 auto; padding:24px 20px 60px; }
  .msg { padding:10px 14px; border-radius:8px; margin-bottom:6px; }
  .msg:hover { background:#161b22; }
  .meta { display:flex; gap:10px; align-items:baseline; }
  .author { font-weight:600; color:#d4af37; }
  .time { color:#6e7681; font-size:12px; }
  .content { white-space:pre-wrap; word-wrap:break-word; }
  .embed { border-left:3px solid #d4af37; background:#161b22; padding:8px 12px; margin:6px 0; border-radius:4px; }
  .et { font-weight:600; margin-bottom:4px; }
  .ed, .ef { color:#c9d1d9; font-size:14px; white-space:pre-wrap; }
  .ef { margin-top:6px; }
  .atts { margin-top:6px; }
  .att { color:#58a6ff; text-decoration:none; font-size:13px; margin-right:8px; }
  footer { text-align:center; color:#6e7681; font-size:12px; padding:20px; }
</style></head>
<body>
<header>
  <h1>#${esc(channel.name)}</h1>
  <div class="sub">
    ${esc(config.communityName)} &middot; ${messages.length} messages &middot; exported ${esc(new Date().toLocaleString())}<br>
    ${meta ? esc(meta) : ''}
  </div>
</header>
<main>${rows || '<p class="sub">No messages.</p>'}</main>
<footer>Transcript generated by the ${esc(config.communityName)} bot.</footer>
</body></html>`;
}

/** Build a Discord attachment containing the channel transcript. */
async function build(channel, meta = '') {
  const messages = await collect(channel);
  const html = renderHtml(channel, messages, meta);
  const file = new AttachmentBuilder(Buffer.from(html, 'utf8'), {
    name: `transcript-${channel.name}-${Date.now()}.html`,
  });
  return { file, count: messages.length };
}

module.exports = { build, collect };
